name: Test Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run ID'
        required: true
        type: string
        default: 'Test run_id'
      run_name:
        description: 'Run Name'
        required: true
        type: string
        default: 'Test run_name'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: node log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.event.inputs.run_id }}
          run_name: ${{ github.event.inputs.run_name }}
