name: Test Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'   # 早报
    - cron: '0 12 * * *'  # 午报
    - cron: '0 18 * * *'  # 晚报
  # workflow_dispatch:
  #   inputs:
  #     run_id:
  #       description: 'Run ID'
  #       required: true
  #       type: string
  #     run_name:
  #       description: 'Run Name'
  #       required: true
  #       type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run wechatpush
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          MY_OPENID: ${{ secrets.MY_OPENID }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          GITHUB_WORKFLOW: ${{ github.workflow }}

          # 0niO7lRJd6_C-oP-TAxK9AuQ_OoLppWnu4r5QtyS0Gg
